import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Heders/Header";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E Shop.2",
  description: "Generated by Azimov Shadcn-ui and Magic-ui,Stripe",
  icons: "/LogoWhite.svg",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className } >
        <Header />
        {children}
      </body>
    </html>
  );
}
